name: "mHome"
description: "mHome Hub integration addon for Home Assistant"
version: "0.0.1"
slug: "mhome"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
auto_update: true
ports:
  8080/tcp: null
map:
  - "share:rw"
  - "ssl"
image: "ghcr.io/mhome-ai/ha-addon:{version}" 