name: "mHome"
description: "mHome Hub integration addon for Home Assistant"
version: "0.1.0"
slug: "mhome"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
auto_update: true
ports:
  9104/tcp: null
ports_description:
  9104/tcp: "mHome web interface"
options:
  port: 9104
schema:
  port: int(1024,65535)?
map:
  - "share:rw"
  - "ssl"
image: "ghcr.io/mhome-ai/ha-addon:{version}" 