name: "mHome"
description: "mHome Hub integration addon for Home Assistant"
version: "0.1.0"
slug: "mhome"
init: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
auto_update: true
map:
  - "share:rw"
  - "ssl"
image: "ghcr.io/mhome-ai/ha-addon"
ingress: true
ingress_port: 9104
panel_title: mHome 